In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
!pip install openpyxl -q

In [4]:
df=pd.read_excel(r'C:\Users\HOME\Documents\AICW\legal triage\triage.xlsx')

In [5]:
df

,case_id,category,subcategory,example_user_problem,risk_level,possible_pathway,documents_or_evidence,possible_authority,source_family,safety_note,legal_citation,disclaimer
0,1,Employment,Unpaid wages,My employer has not paid my wages for the last...,Medium,Labour/employment grievance pathway; verify th...,Employment records; salary slips; bank stateme...,Relevant DLSA/TLSC or competent labour authori...,India Code / NALSA / relevant labour authority,Triage only; verify current procedure and juri...,"Payment of Wages Act, 1936, Section 15 (claim ...","This is legal-information triage, not legal ad..."
1,2,Employment,Unpaid wages,My company keeps delaying my pending salary.,Medium,Labour/employment grievance pathway; verify th...,Employment records; salary slips; bank stateme...,Relevant DLSA/TLSC or competent labour authori...,India Code / NALSA / relevant labour authority,Triage only.,"Payment of Wages Act, 1936, Section 15 (claim ...","This is legal-information triage, not legal ad..."
2,3,Employment,Unpaid wages,I have not received my salary for two months a...,Medium,Labour/employment grievance pathway; verify th...,Employment records; salary slips; bank stateme...,Relevant DLSA/TLSC or competent labour authori...,India Code / NALSA / relevant labour authority,Triage only; verify current procedure and juri...,"Payment of Wages Act, 1936, Section 15 (claim ...","This is legal-information triage, not legal ad..."
3,4,Employment,Unpaid wages,My factory owner has withheld my daily wages f...,Medium,Labour/employment grievance pathway; verify th...,Employment records; salary slips; bank stateme...,Relevant DLSA/TLSC or competent labour authori...,India Code / NALSA / relevant labour authority,Triage only.,"Payment of Wages Act, 1936, Section 15 (claim ...","This is legal-information triage, not legal ad..."
4,5,Employment,Unpaid wages,My contractor is refusing to pay the wages owe...,Medium,Labour/employment grievance pathway; verify th...,Employment records; salary slips; bank stateme...,Relevant DLSA/TLSC or competent labour authori...,India Code / NALSA / relevant labour authority,Triage only; verify current procedure and juri...,"Payment of Wages Act, 1936, Section 15 (claim ...","This is legal-information triage, not legal ad..."
...,...,...,...,...,...,...,...,...,...,...,...,...
129,130,Other,RTI/administrative issue,I applied for a government document months ago...,Low,Administrative/RTI process may apply; may not ...,Application copy; acknowledgment/receipt; ID p...,Relevant government department; Legal Services...,NALSA / India Code / relevant official authority,Confirm whether this is purely administrative ...,"Right to Information Act, 2005, Sections 6-7 (...","This is legal-information triage, not legal ad..."
130,131,Other,RTI/administrative issue,A government office is not processing my appli...,Low,Administrative/RTI process may apply; may not ...,Application copy; acknowledgment/receipt; ID p...,Relevant government department; Legal Services...,NALSA / India Code / relevant official authority,Confirm whether this is purely administrative ...,"Right to Information Act, 2005, Sections 6-7 (...","This is legal-information triage, not legal ad..."
131,132,Other,RTI/administrative issue,I lost important identity documents and don't ...,Low,Administrative/RTI process may apply; may not ...,Application copy; acknowledgment/receipt; ID p...,Relevant government department; Legal Services...,NALSA / India Code / relevant official authority,Confirm whether this is purely administrative ...,"Right to Information Act, 2005, Sections 6-7 (...","This is legal-information triage, not legal ad..."
132,133,Other,RTI/administrative issue,My pension payments have stopped without any e...,Low,Administrative/RTI process may apply; may not ...,Application copy; acknowledgment/receipt; ID p...,Relevant government department; Legal Services...,NALSA / India Code / relevant official authority,Confirm whether this is purely administrative ...,"Right to Information Act, 2005, Sections 6-7 (...","This is legal-information triage, not legal ad..."
133,134,Other,RTI/administrative issue,I want to report corruption by a local governm...,Low,Administrative/RTI process may apply; may not ...,Application copy; acknowledgment/receipt; ID p...,Relevant government department; Legal Services...,NALSA / India Code / relevant official authority,Confirm whether this is purely administrative ...,"Right to Information Act, 2005, Sections 6-7 (...","This is legal-information triage, not legal ad..."

In [6]:
df.columns

Index(['case_id', 'category', 'subcategory', 'example_user_problem',
       'risk_level', 'possible_pathway', 'documents_or_evidence',
       'possible_authority', 'source_family', 'safety_note', 'legal_citation',
       'disclaimer'],
      dtype='str')

In [7]:
df.isnull().sum()

case_id                  0
category                 0
subcategory              0
example_user_problem     0
risk_level               0
possible_pathway         0
documents_or_evidence    0
possible_authority       0
source_family            0
safety_note              0
legal_citation           0
disclaimer               0
dtype: int64

In [8]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [10]:
df["clean_text"] = df["example_user_problem"].apply(clean_text)
df.columns.tolist()

['case_id',
 'category',
 'subcategory',
 'example_user_problem',
 'risk_level',
 'possible_pathway',
 'documents_or_evidence',
 'possible_authority',
 'source_family',
 'safety_note',
 'legal_citation',
 'disclaimer',
 'clean_text']

In [11]:
X = df["clean_text"]
y_category = df["category"]
y_risk = df["risk_level"]

In [12]:
X_train, X_test, y_cat_train, y_cat_test = train_test_split(
    X, y_category, test_size=0.2, random_state=42
)

In [13]:
X_train

11        i was fired without any notice or reason given
51     the insurance company is delaying settlement o...
93     i need information about seeking maintenance a...
122    i am not sure if my problem is a legal matter ...
125    someone hacked my social media account and is ...
                             ...
71     an unknown person keeps following me and messa...
106    as a daily wage worker i cannot afford court f...
14     my employer dismissed me verbally with no lett...
92     i want to know how to file for judicial separa...
102    i want to legally adopt a child and don t know...
Name: clean_text, Length: 107, dtype: str

In [14]:
X_test

127    my elderly parents are not being cared for by ...
66     i am being sexually harassed by my manager at ...
104    i have a legal problem but cannot afford a law...
19     i am being bullied by my manager and it is aff...
42     i cancelled a service subscription but keep ge...
60     i am facing constant violence at home and want...
12     my company terminated me while i was on medica...
109        how do i find the dlsa office for my district
100    my spouse and i have mutually agreed to divorc...
101    i want a divorce but my spouse is not cooperat...
44     i paid an interior decorator in advance but th...
40     i returned a defective item two months ago but...
27     i work through a labour contractor and neither...
47     i paid for a product online but it was never d...
73     a neighbour keeps watching and following me an...
31     i have not been compensated for overtime work ...
83     a tenant is refusing to vacate my property eve...
4      my contractor is refusing to pay the wages owe...
64     someone is sending me threatening messages aft...
97     my former spouse is not allowing me to see our...
84     my landlord is refusing to return my security ...
26     i resigned but my pf withdrawal has been pendi...
16     my contract was not renewed after i raised a s...
18     my supervisor keeps shouting and insulting me ...
10     i was removed from my job and do not know wher...
110    which legal aid office should i contact for my...
45     a travel agency collected my payment but cance...
Name: clean_text, dtype: str

In [15]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [16]:
category_clf = LogisticRegression(max_iter=1000, class_weight="balanced")
category_clf.fit(X_train_vec, y_cat_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [17]:
cat_preds = category_clf.predict(X_test_vec)
print(classification_report(y_cat_test, cat_preds, zero_division=0))

                precision    recall  f1-score   support

      Consumer       0.80      0.80      0.80         5
    Employment       0.75      0.67      0.71         9
        Family       0.50      1.00      0.67         3
     Legal Aid       1.00      1.00      1.00         3
         Other       0.00      0.00      0.00         1
      Property       1.00      0.50      0.67         2
Women's Safety       0.67      0.50      0.57         4

      accuracy                           0.70        27
     macro avg       0.67      0.64      0.63        27
  weighted avg       0.74      0.70      0.70        27

In [18]:
X_train2, X_test2, y_risk_train, y_risk_test = train_test_split(
    X, y_risk, test_size=0.2, random_state=42
)

X_train2_vec = vectorizer.transform(X_train2)
X_test2_vec = vectorizer.transform(X_test2)

risk_clf = LogisticRegression(max_iter=1000, class_weight="balanced")
risk_clf.fit(X_train2_vec, y_risk_train)

risk_preds = risk_clf.predict(X_test2_vec)
print(classification_report(y_risk_test, risk_preds, zero_division=0))

              precision    recall  f1-score   support

        High       0.60      0.50      0.55         6
         Low       0.50      0.67      0.57         3
      Medium       0.78      0.78      0.78        18

    accuracy                           0.70        27
   macro avg       0.63      0.65      0.63        27
weighted avg       0.71      0.70      0.70        27

In [19]:
retrieval_vectorizer = TfidfVectorizer(ngram_range=(1, 2))
retrieval_matrix = retrieval_vectorizer.fit_transform(df["clean_text"])

In [20]:
def find_similar_case(user_text, top_k=1):
    cleaned = clean_text(user_text)
    query_vec = retrieval_vectorizer.transform([cleaned])
    sims = cosine_similarity(query_vec, retrieval_matrix)[0]
    top_idx = sims.argsort()[::-1][:top_k]
    return df.iloc[top_idx]

# quick test
find_similar_case("my boss hasn't paid me in two months")

,case_id,category,subcategory,example_user_problem,risk_level,possible_pathway,documents_or_evidence,possible_authority,source_family,safety_note,legal_citation,disclaimer,clean_text
2,3,Employment,Unpaid wages,I have not received my salary for two months a...,Medium,Labour/employment grievance pathway; verify th...,Employment records; salary slips; bank stateme...,Relevant DLSA/TLSC or competent labour authori...,India Code / NALSA / relevant labour authority,Triage only; verify current procedure and juri...,"Payment of Wages Act, 1936, Section 15 (claim ...","This is legal-information triage, not legal ad...",i have not received my salary for two months a...

In [21]:
def predict_triage(user_text, top_k=1):
    cleaned = clean_text(user_text)

    # Category prediction
    cat_vec = vectorizer.transform([cleaned])
    predicted_category = category_clf.predict(cat_vec)[0]

    # Risk prediction
    predicted_risk = risk_clf.predict(cat_vec)[0]

    # Retrieve the closest matching real case
    match = find_similar_case(user_text, top_k=top_k).iloc[0]

    result = {
        "input_text": user_text,
        "predicted_category": predicted_category,
        "predicted_risk_level": predicted_risk,
        "matched_subcategory": match["subcategory"],
        "possible_pathway": match["possible_pathway"],
        "documents_or_evidence": match["documents_or_evidence"],
        "possible_authority": match["possible_authority"],
        "legal_citation": match["legal_citation"],
        "safety_note": match["safety_note"],
    }
    return result

# test it
predict_triage("my boss hasn't paid me in two months")

{'input_text': "my boss hasn't paid me in two months",
 'predicted_category': 'Employment',
 'predicted_risk_level': 'Medium',
 'matched_subcategory': 'Unpaid wages',
 'possible_pathway': 'Labour/employment grievance pathway; verify the competent authority for the facts and location.',
 'documents_or_evidence': 'Employment records; salary slips; bank statements; attendance records; messages/emails; ID proof.',
 'possible_authority': "Relevant DLSA/TLSC or competent labour authority. [Karnataka: nearest DLSA/TLSC per applicant's district, e.g. DLSA Davanagere, Old Court Complex, P.J Extension, Davanagere-577002, Ph: 08192-296364; KSLSA, Nyaya Degula Building, H. Siddaiah Road, Bengaluru-560027, Ph: 080-22111730; NALSA toll-free helpline 15100]",
 'legal_citation': 'Payment of Wages Act, 1936, Section 15 (claim before the Authority for Payment of Wages); Code on Wages, 2019.',
 'safety_note': 'Triage only; verify current procedure and jurisdiction.'}

In [22]:
print(predict_triage("someone is stalking me and I'm scared"))
print(predict_triage("my landlord won't return my security deposit"))
print(predict_triage("I want to adopt a child legally"))

{'input_text': "someone is stalking me and I'm scared", 'predicted_category': "Women's Safety", 'predicted_risk_level': 'High', 'matched_subcategory': 'Stalking/harassment', 'possible_pathway': 'Safety-first response; may involve local police and Legal Services Institution support.', 'documents_or_evidence': 'Screenshots; messages; witness details; prior complaints; ID proof.', 'possible_authority': "Relevant local authority and Legal Services Institution; urgent danger requires immediate official help. [Karnataka: nearest DLSA/TLSC per applicant's district, e.g. DLSA Davanagere, Old Court Complex, P.J Extension, Davanagere-577002, Ph: 08192-296364; KSLSA, Nyaya Degula Building, H. Siddaiah Road, Bengaluru-560027, Ph: 080-22111730; NALSA toll-free helpline 15100]", 'legal_citation': 'Bharatiya Nyaya Sanhita, 2023, Section 78 (stalking - corresponds to former IPC Section 354D).', 'safety_note': 'Safety information must be prioritized.'}
{'input_text': "my landlord won't return my security deposit", 'predicted_category': 'Employment', 'predicted_risk_level': 'Medium', 'matched_subcategory': 'Illegal possession/tenancy dispute', 'possible_pathway': 'Civil/tenancy pathway may be relevant depending on facts and local rent-control law.', 'documents_or_evidence': 'Title/lease documents; notices sent; photographs; correspondence; ID proof.', 'possible_authority': "Relevant DLSA/TLSC or competent civil/revenue authority. [Karnataka: nearest DLSA/TLSC per applicant's district, e.g. DLSA Davanagere, Old Court Complex, P.J Extension, Davanagere-577002, Ph: 08192-296364; KSLSA, Nyaya Degula Building, H. Siddaiah Road, Bengaluru-560027, Ph: 080-22111730; NALSA toll-free helpline 15100]", 'legal_citation': 'Karnataka Land Revenue Act, 1964 (Record of Rights); applicable Rent Control legislation for tenancy matters.', 'safety_note': 'Forum and procedure depend on current law and facts.'}
{'input_text': 'I want to adopt a child legally', 'predicted_category': 'Family', 'predicted_risk_level': 'Medium', 'matched_subcategory': 'Adoption/guardianship', 'possible_pathway': 'Family/civil-court and legal-aid pathway may be relevant depending on applicable law.', 'documents_or_evidence': 'ID proof; relevant family documents; death/consent certificates if applicable.', 'possible_authority': "Relevant DLSA/TLSC and competent family/civil forum. [Karnataka: nearest DLSA/TLSC per applicant's district, e.g. DLSA Davanagere, Old Court Complex, P.J Extension, Davanagere-577002, Ph: 08192-296364; KSLSA, Nyaya Degula Building, H. Siddaiah Road, Bengaluru-560027, Ph: 080-22111730; NALSA toll-free helpline 15100]", 'legal_citation': 'Hindu Adoptions and Maintenance Act, 1956; Guardians and Wards Act, 1890; Juvenile Justice (Care and Protection of Children) Act, 2015 for CARA-route adoptions.', 'safety_note': 'Triage only; verify current procedure and jurisdiction.'}

In [23]:
SAFETY_KEYWORDS = ["hit", "abuse", "threat", "unsafe", "afraid", "violence", "stalk", "assault"]

def add_safety_flag(result):
    text_lower = result["input_text"].lower()
    is_urgent = (
        result["predicted_category"] == "Women's Safety"
        or result["predicted_risk_level"] == "High"
        or any(k in text_lower for k in SAFETY_KEYWORDS)
    )
    result["urgent_flag"] = is_urgent
    return result

predict_triage("my husband hits me and I don't know who to call")

{'input_text': "my husband hits me and I don't know who to call",
 'predicted_category': "Women's Safety",
 'predicted_risk_level': 'High',
 'matched_subcategory': 'Domestic violence',
 'possible_pathway': 'Safety-first response; relevant protection/legal process and legal-aid support may be available.',
 'documents_or_evidence': 'ID proof; messages; photographs; medical records if any; previous complaints; other evidence.',
 'possible_authority': "Relevant local authority and Legal Services Institution; urgent danger requires immediate official help. [Karnataka: nearest DLSA/TLSC per applicant's district, e.g. DLSA Davanagere, Old Court Complex, P.J Extension, Davanagere-577002, Ph: 08192-296364; KSLSA, Nyaya Degula Building, H. Siddaiah Road, Bengaluru-560027, Ph: 080-22111730; NALSA toll-free helpline 15100]",
 'legal_citation': 'Protection of Women from Domestic Violence Act, 2005, Section 12 (application to Magistrate) and Section 5 (duties of Protection Officer/police).',
 'safety_note': 'Safety information must be prioritized.'}

In [24]:
import joblib
joblib.dump({
    "category_clf": category_clf,
    "risk_clf": risk_clf,
    "vectorizer": vectorizer,
    "retrieval_vectorizer": retrieval_vectorizer,
    "retrieval_matrix": retrieval_matrix,
    "df": df
}, "triage_model.joblib")

['triage_model.joblib']

In [25]:
import json

with open("corpus.json", "r", encoding="utf-8") as f:
    corpus = json.load(f)

corpus_df = pd.DataFrame(corpus)
corpus_df["clean_text"] = corpus_df["text"].apply(clean_text)
corpus_df.head()

,id,act,section,category,text,clean_text
0,pow_15,"Payment of Wages Act, 1936",Section 15,Employment,An employee whose wages have been delayed or n...,an employee whose wages have been delayed or n...
1,id_act_2a,"Industrial Disputes Act, 1947",Section 2A,Employment,"A dismissal, discharge, retrenchment, or termi...",a dismissal discharge retrenchment or terminat...
2,posh_4,Sexual Harassment of Women at Workplace (Preve...,Section 4,Employment,Every workplace employing 10 or more employees...,every workplace employing 10 or more employees...
3,epf_act_8,Employees' Provident Funds and Miscellaneous P...,Section 8,Employment,If an employer fails to deposit PF contributio...,if an employer fails to deposit pf contributio...
4,cpa_35,"Consumer Protection Act, 2019",Section 35,Consumer,A consumer complaint regarding defective goods...,a consumer complaint regarding defective goods...

In [26]:
statute_vectorizer = TfidfVectorizer(ngram_range=(1, 2))
statute_matrix = statute_vectorizer.fit_transform(corpus_df["clean_text"])

def retrieve_statutes(user_text, category=None, top_k=2):
    cleaned = clean_text(user_text)
    query_vec = statute_vectorizer.transform([cleaned])
    sims = cosine_similarity(query_vec, statute_matrix)[0]

    if category:
        boost = corpus_df["category"].apply(lambda c: 0.15 if c == category else 0)
        sims = sims + boost.values

    top_idx = sims.argsort()[::-1][:top_k]
    return corpus_df.iloc[top_idx][["act", "section", "text"]]

# test it
retrieve_statutes("my husband hits me and threatens me", category="Women's Safety")

,act,section,text
10,"Dowry Prohibition Act, 1961",Section 3,Giving or taking dowry is a punishable offence...
8,"Bharatiya Nyaya Sanhita, 2023 (formerly IPC Se...",Stalking provision,Following or repeatedly contacting a woman des...

In [27]:
def predict_triage(user_text, top_k=1):
    cleaned = clean_text(user_text)
    cat_vec = vectorizer.transform([cleaned])
    predicted_category = category_clf.predict(cat_vec)[0]
    predicted_risk = risk_clf.predict(cat_vec)[0]

    match = find_similar_case(user_text, top_k=top_k).iloc[0]
    statutes = retrieve_statutes(user_text, category=predicted_category, top_k=2)

    text_lower = user_text.lower()
    is_urgent = (
        predicted_category == "Women's Safety"
        or predicted_risk == "High"
        or any(k in text_lower for k in SAFETY_KEYWORDS)
    )

    return {
        "predicted_category": predicted_category,
        "predicted_risk_level": predicted_risk,
        "possible_pathway": match["possible_pathway"],
        "documents_or_evidence": match["documents_or_evidence"],
        "possible_authority": match["possible_authority"],
        "legal_citation": match["legal_citation"],
        "retrieved_statutes": statutes.to_dict(orient="records"),
        "safety_note": match["safety_note"],
        "urgent_flag": is_urgent,
    }

predict_triage("my husband hits me and threatens me")

{'predicted_category': "Women's Safety",
 'predicted_risk_level': 'High',
 'possible_pathway': 'Legal-aid eligibility and the appropriate family/legal process should be checked.',
 'documents_or_evidence': 'ID proof; marriage/family documents if applicable; financial records; relevant notices.',
 'possible_authority': "Relevant DLSA/TLSC or other Legal Services Institution. [Karnataka: nearest DLSA/TLSC per applicant's district, e.g. DLSA Davanagere, Old Court Complex, P.J Extension, Davanagere-577002, Ph: 08192-296364; KSLSA, Nyaya Degula Building, H. Siddaiah Road, Bengaluru-560027, Ph: 080-22111730; NALSA toll-free helpline 15100]",
 'legal_citation': 'Section 144, Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023 (maintenance of wives, children, parents) - re-enacts former Section 125, Code of Criminal Procedure, 1973, effective 1 July 2024; Hindu Adoptions and Maintenance Act, 1956, Section 18.',
 'retrieved_statutes': [{'act': 'Dowry Prohibition Act, 1961',
   'section': 'Section 3',
   'text': "Giving or taking dowry is a punishable offence. Harassment for dowry can also be reported under the Bharatiya Nyaya Sanhita's cruelty-by-husband-or-relatives provision, alongside relief under the Domestic Violence Act."},
  {'act': 'Bharatiya Nyaya Sanhita, 2023 (formerly IPC Section 354D)',
   'section': 'Stalking provision',
   'text': 'Following or repeatedly contacting a woman despite her clear disinterest, or monitoring her use of the internet/email/electronic communication, constitutes stalking and is a criminal offence that can be reported to the police.'}],
 'safety_note': 'Do not promise eligibility or outcome.',
 'urgent_flag': True}